[package]
name = "subscription_protocol"
version = "1.0.0"
authors = []

[addresses]
subscription = "0xdc41a9c2956e2a2655481fac6b86bd0cabcfb451e82e31eb74741d7ccda20168"
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "mainnet"

[dev-dependencies]
